import type { StyleThemeColors } from '../../types';

export const DEFAULT_POSITRON_THEME_COLORS: StyleThemeColors = {
	background: '#f2f3f0',
	park: '#d2e8d4',
	residential: '#e4e4e4',
	forest: '#d2e8d4',
	ice: '#e8f4f4',
	water: '#cad2d3',
	waterway: '#cad2d3',
	building: '#d9dad8',
	buildingOutline: '#d9dad8',
	path: '#ffffff',
	roadMinor: '#ffffff',
	roadMajorCasing: '#e5e5e5',
	roadMajorFill: '#ffffff',
	motorwayCasing: '#e5e5e5',
	motorwayFill: '#ffffff',
	rail: '#dcdcdc',
	railDash: '#ffffff',
	boundary: '#c3c3c3',
	aerowayLine: '#e0e0e0',
	aerowayArea: '#d1d1d1',
	waterLabel: '#7a7a7a',
	waterLabelHalo: '#ffffff',
	roadLabel: '#666666',
	roadLabelHalo: '#ffffff',
	placeLabel: '#333333',
	placeLabelHalo: '#ffffff',
};
